title: Donna Atkinson # your name (or website title) here
logo: "images/Blue-2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven Chemistry Educator turned Data Analyst 
  Please look around. I have projects listed here that are personal
  and from school. Enjoy! <br><br>
  I am currenlty seeking a Junior Data Analyst role, 
  please email me at datadonna9@gmail.com <br><br>
  <a href="https://www.linkedin.com/in/data-donna/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
